### ISSUE TITLE
Add a warning message to "paper.disable-move-event"

### ISSUE THREAD

**Issue by AZFire1** [TimingsBotFork/Timings-Bot#10]
My suggestion is to add a small warning message to the timings report analyzer for the paper.yml "hopper.disable-move-event" config option. It currently recommends you set it to true, without any extra info. If people have protection plugins such as Lockette, chest protect, or any other plugin. This option set to true allows players on these servers to steal items from locked containers of other players by placing hoppers beneath them. I learned this the hard way a while ago when I had this option set to true.

**Comment by stijnb1234** [comment]
Currently, it's ignoring if you have some of those events.

**Comment by AZFire1** [comment]
@stijnb1234 yeah I know.. I don't know why I have this still open, I talked with Fredurado and we got it all sorted out roughly a week or two ago.
